In [2]:
import numpy as np

In [12]:
N = 150
R = 0.15
#u0 = 1.257*10**(-6)
u0 = 4*np.pi*10**(-7)
I = np.array([3.30, 2.08, 1.52, 1.22])

In [13]:
B = (1 / ((5/4)**(3/2)))*((N*u0*I)/(R))

In [14]:
B

array([0.00296728, 0.00187029, 0.00136675, 0.001097  ])

In [19]:
np.sqrt(2*(1.758*10**(11))*(170))

7731235.347601313

In [22]:
V = 170
r = np.array([0.02,0.03,0.04,0.05])
c_m = (2*V)/((r**2) * (B**2))

In [23]:
c_m

array([9.65386801e+10, 1.07999078e+11, 1.13758032e+11, 1.13013300e+11])

In [24]:
I2 = 1.5
B2 = (1 / ((5/4)**(3/2)))*((N*u0*I2)/(R))

In [25]:
B2

0.0013487644283598193

In [26]:
V2 = np.array([65.4,
118.9,
169.5,
249.2])
c_m2 = (2*V2)/((r**2) * (B2**2))

In [27]:
c_m2

array([1.79752751e+11, 1.45243643e+11, 1.16468239e+11, 1.09588711e+11])

In [46]:
np.abs(c_m - 1.758820*(10**(11)))/(1.758820*(10**(11)))*100

array([45.11167707, 38.59571861, 35.32139059, 35.74481733])

In [47]:
np.abs(c_m - 1.758820*(10**(11)))

array([7.93433199e+10, 6.78829218e+10, 6.21239682e+10, 6.28686996e+10])

In [48]:
np.abs(c_m2 - 1.758820*(10**(11)))/(1.758820*(10**(11)))*100

array([ 2.20076581, 17.41983653, 33.7804671 , 37.69191232])

In [49]:
np.abs(c_m2 - 1.758820*(10**(11)))

array([3.87075093e+09, 3.06383569e+10, 5.94137612e+10, 6.62932892e+10])