In [1]:
import numpy as np
import time

In [ ]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(str(1000*(toc-tic))+"ms")

In [6]:
A = np.array(([56, 0, 4.4, 68],
            [1.2, 104, 52, 8],
            [1.8, 135, 99, 0.9]))
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [8]:
total = A.sum(axis=0)
total

array([ 59. , 239. , 155.4,  76.9])

In [9]:
total.reshape(1,4)

array([[ 59. , 239. , 155.4,  76.9]])

In [14]:
100*A/total

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [16]:
100*A/total.reshape(1,4)

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [21]:
np.array([
    [[1],[2]],
    [[3],[4]]
]).shape()

TypeError: 'tuple' object is not callable

In [2]:
np.array([[[1],[2]],[[3],[4]]]).shape()

TypeError: 'tuple' object is not callable

In [4]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b 

In [5]:
c

array([[-0.43875861,  0.29644052,  0.37614915],
       [ 0.29039635, -0.20850926, -0.22238993],
       [-0.31858622, -0.30651356, -0.40220525]])